const express = require('express');
const { check } = require('express-validator');
const userController = require("../controllers/user-controller");
const router = express.Router();
router.get('/signup', userController.signupPage);
router.post('/signup', userController.signup);
router.get('/admin', userController.adminPage);
router.get('/user', userController.userPage);
router.get('/signin', userController.signPage);
router.post('/signin', userController.login);
router.get('/logout', userController.userLogout);
router.delete('/:uid', userController.userDelete);
router.post('/edit', userController.userUpdate);
router.put('/update/:uid', userController.findUpdate);
module.exports = router;